### PR TITLE
improve / fix help module, fix #258 and #244

### LINKED ISSUE #258: Missing keybind in menu and script error on mission start
This was reported multiple times already, but no one bothered to post a RPT. The root cause for it was already fixed, but there are still people out there that occasionally have the issue, due to these entries remaining in the profileNamespace.

```
15:27:29 Error in expression <_mod = _keyBind select 1;
_shift = _mod select 0;
_ctrl = _mod select 1;
_alt = >
15:27:29   Error position: <select 0;
_ctrl = _mod select 1;
_alt = >
15:27:29   Error select: Type Number, expected Array,String,Config entry
15:27:29 File x\cba\addons\help\XEH_postClientInit.sqf, line 64
```

### PR DESCRIPTION
**Pull request by commy2**
- fixes #258 (hopefully) and #244
- fixes: mods in main menu now auto cycle even when `-world="empty"`
- fixes: addKeyinding keys don't overwrite the help diary entry of all config based key handlers anymore
- uses new scripting commands (`private` keyword, `configClasses`, `params` etc.)
- uses faster `createNamespace` instead of hashes
- removes header files that are in Arma already and includes them instead
- removes `CBA_help_fnc_describe`, because it's never used, not documented and does no longer work sufficiently in A3
- adds function headers, uses macros where appropriate, etc.

### CODE REVIEW

File: addons/help/config.cpp [hunk 1]
```diff
@@ -14,3 +14,5 @@ class CfgPatches {
 
 #include "CfgEventhandlers.hpp"
 #include "CfgRscStd.hpp"
+
+//#include "test_key.hpp"
```
Comment (Killswitch00) [inline addons/help/config.cpp]: Is this needed?

File: addons/help/stringtable.xml [hunk 2]
```diff
@@ -1,60 +1,62 @@
 <?xml version="1.0" encoding="UTF-8"?>
-<Project name="Arma2"><Package name="CBA">
+<Project name="Arma2">
```
Comment (Killswitch00) [inline addons/help/stringtable.xml]: Should this be bumped to Arma3?
