### PR TITLE
Transitional animal randomization fix for 1.48/1.50. Fixes #114.

### LINKED ISSUE #114: RPT Spam Error in expression </*--------------------------------------> in A3 1.50
1.50RC and DEV Branch. 

CBA causes the following RPT Spam 

<pre>10:55:51 Error in expression </*-------------------------------------->
10:55:51   Error position: </*-------------------------------------->
10:55:51   Error Invalid number in expression
10:55:51 Error in expression </*-------------------------------------->
10:55:51   Error position: </*-------------------------------------->
10:55:51   Error Invalid number in expression
10:55:54 No owner
10:55:54 Error in expression </*-------------------------------------->
10:55:54   Error position: </*-------------------------------------->
10:55:54   Error Invalid number in expression
10:55:54 Error in expression </*-------------------------------------->
10:55:54   Error position: </*-------------------------------------->
10:55:54   Error Invalid number in expression
10:55:55 No owner
10:55:55 Error in expression </*-------------------------------------->
10:55:55   Error position: </*-------------------------------------->
10:55:55   Error Invalid number in expression
10:55:55 Error in expression </*-------------------------------------->
10:55:55   Error position: </*-------------------------------------->
10:55:55   Error Invalid number in expression</pre>

STEPS TO REPO:
1. Run COOP 07 Headhunters mission or it has been reported any mission. 
2. Get boots on the ground.
Observe RPT SPAM

Confirmed does not happen with no mods.

### PR DESCRIPTION
**Pull request by robalo**

### CODE REVIEW

File: addons/xeh_a3/CfgEventHandlers.hpp [hunk 1]
```diff
@@ -159,20 +159,26 @@ class Extended_init_Eventhandlers {
...
+                SLX_BIS = "_FRnd = compile preprocessFile ""\A3\animals_f_beta\goat\scripts\randomize.sqf"";(_this select 0) call _FRnd;";
         };
         class Sheep_random_F /* : Animal_Base_F */ {
-                SLX_BIS = "_FRnd = compile loadFile ""\A3\animals_f_beta\Sheep\scripts\randomize.sqf"";(_this select 0) call _FRnd;";
+                SLX_BIS = "_FRnd = compile preprocessFile ""\A3\animals_f_beta\Sheep\scripts\randomize.sqf"";(_this select 0) call _FRnd;";
         };
-        class Snake_random_F /* : Animal_Base_F */ {
-                SLX_BIS = "_FRnd = compile loadFile ""\A3\animals_f\Snakes\scripts\randomize.sqf"";(_this select 0) call _FRnd;";
+        class Cock_random_F /* : Fowl_Base_F */ {
+                SLX_BIS = "_FRnd = compile preprocessFile ""\A3\animals_f_beta\Chicken\scripts\randomize.sqf"";(_this select 0) call _FRnd;";
```
Comment (Killswitch00) [inline addons/xeh_a3/CfgEventHandlers.hpp]: Cock_random_F is not randomized in 1.48 (it does not have an init event handler). We can still add it into a pre-A3 1.50 XEH release, but with a forward-looking XEH init event handler - the one that the animal will have in 1.50: ```(_this select 0) call bis_fnc_animalRandomization;```

That way it will do nothing in 1.48 and work as intended in 1.50.

Comment (robalo) [inline addons/xeh_a3/CfgEventHandlers.hpp]: It does actually work with 1.48, looks like it was missed by BIS.
