### PR TITLE
JAM - Add 1.92 vanilla mag wells

### LINKED ISSUE #1132: Magazine wells 1.92 compatibility
**Arma 3 Version:** `1.92` stable
**CBA Version:** `3.10.1` stable

**Mods:**
```
- CBA_A3
```

**Description:**
- Dynamic Magazine (Proxies) possible issues. i.e: For MX 6.5mm (sand) you cannot attach a 6.5mm black 30 round magazine. But without CBA loaded you can.

**Steps to reproduce:**
- Try loading a 6.5mm 30 round black magazine into the MX (sand) in Tanoa as a Blufor rifleman

**Where did the issue occur?**
- Editor (Singleplayer)

### PR DESCRIPTION
**Pull request by PabstMirror**
close #1132

### CODE REVIEW

**Comment by PabstMirror** [comment]
vanilla:
```
launch_NLAW_F - ["NLAW"]
launch_RPG32_F - ["RPG32"]
launch_Titan_base - ["Titan_Long"]
launch_Titan_short_base - ["Titan_Short"]
DMR_01_base_F - ["Rahim_762x54"]
EBR_base_F - ["M14_762x51"]
GM6_base_F - []
LRR_base_F - ["M320_408"]
hgun_ACPC2_F - ["ACPC2_45ACP"]
hgun_P07_F - ["Pistol_9x21"]
hgun_Pistol_heavy_01_F - ["PistolHeavy_01_45ACP"]
hgun_Pistol_heavy_02_F - ["Cylinder_45ACP"]
hgun_Rook40_F - ["Pistol_9x21"]
arifle_Katiba_Base_F - ["Katiba_65x39"]
mk20_base_F - ["STANAG_556x45"]
arifle_MX_Base_F - ["MX_65x39","MX_65x39_Large"]
SDAR_base_F - ["STANAG_556x45"]
Tavor_base_F - ["STANAG_556x45"]
DMR_02_base_F - ["MAR10_338"]
DMR_03_base_F - ["M14_762x51"]
DMR_04_base_F - ["ASP1_127x54"]
DMR_05_base_F - ["Cyrus_93"]
DMR_06_base_F - ["M14_762x51"]
launch_RPG7_F - ["RPG7"]
arifle_AK12_base_F - ["AK_762x39"]
arifle_AKM_base_F - ["AK_762x39"]
arifle_AKS_base_F - ["AK_545x39"]
arifle_ARX_base_F - ["Katiba_65x39"]
arifle_CTAR_base_F - ["CTAR_580x42","CTAR_580x42_Large"]
arifle_CTARS_base_F - ["CTAR_580x42","CTAR_580x42_Large"]
arifle_SPAR_01_base_F - ["STANAG_556x45","STANAG_556x45_Large"]
arifle_SPAR_02_base_F - ["STANAG_556x45","STANAG_556x45_Large"]
```
cba:
```
UGL_F - ["CBA_40mm_M203","CBA_40mm_EGLM"]
launch_NLAW_F - ["NLAW"]
launch_RPG32_F - ["RPG32"]
launch_Titan_base - ["Titan_Long"]
launch_Titan_short_base - ["Titan_Short"]
DMR_01_base_F - ["Rahim_762x54","CBA_762x54R_SVD"]
EBR_base_F - ["M14_762x51","CBA_762x51_M14"]
GM6_base_F - []
LRR_base_F - ["M320_408"]
LMG_Mk200_F - ["CBA_65x39_Mk200"]
LMG_Zafir_F - ["CBA_762x54R_LINKS"]
hgun_ACPC2_F - ["ACPC2_45ACP"]
hgun_P07_F - ["Pistol_9x21"]
hgun_Pistol_heavy_01_F - ["PistolHeavy_01_45ACP"]
hgun_Pistol_heavy_02_F - ["Cylinder_45ACP"]
hgun_Rook40_F - ["Pistol_9x21"]
arifle_Katiba_Base_F - ["Katiba_65x39","CBA_65x39_Katiba"]
mk20_base_F - ["STANAG_556x45","CBA_556x45_STANAG","CBA_556x45_STANAG_L","CBA_556x45_STANAG_XL","CBA_556x45_STANAG_2D"]
arifle_MX_Base_F - ["MX_65x39","MX_65x39_Large","CBA_65x39_MX"]
SDAR_base_F - ["STANAG_556x45","CBA_556x45_STANAG"]
Tavor_base_F - ["STANAG_556x45","CBA_556x45_STANAG","CBA_556x45_STANAG_L","CBA_556x45_STANAG_XL","CBA_556x45_STANAG_2D"]
SMG_01_Base - ["CBA_45ACP_Glock_Full"]
SMG_02_base_F - ["CBA_9x19_ScorpionEvo3"]
DMR_02_base_F - ["MAR10_338"]
DMR_03_base_F - ["M14_762x51","CBA_762x51_MkI_EMR"]
DMR_04_base_F - ["ASP1_127x54"]
DMR_05_base_F - ["Cyrus_93"]
DMR_06_base_F - ["M14_762x51","CBA_762x51_M14"]
MMG_01_base_F - ["CBA_93x64_LINKS"]
MMG_02_base_F - ["CBA_338NM_LINKS"]
SMG_03_TR_BASE - ["CBA_57x28_P90"]
launch_RPG7_F - ["RPG7","CBA_RPG7"]
LMG_03_base_F - ["CBA_556x45_MINIMI"]
arifle_AK12_base_F - ["AK_762x39","CBA_762x39_AK","CBA_762x39_RPK"]
arifle_AKM_base_F - ["AK_762x39","CBA_762x39_AK","CBA_762x39_RPK"]
arifle_AKS_base_F - ["AK_545x39","CBA_545x39_AK","CBA_545x39_RPK"]
arifle_ARX_base_F - ["Katiba_65x39","CBA_65x39_Katiba"]
arifle_CTAR_base_F - ["CTAR_580x42","CTAR_580x42_Large","CBA_580x42_TYPE95","CBA_580x42_TYPE95_XL"]
arifle_CTARS_base_F - ["CTAR_580x42","CTAR_580x42_Large","CBA_580x42_TYPE95","CBA_580x42_TYPE95_XL"]
arifle_SPAR_01_base_F - ["STANAG_556x45","CBA_556x45_STANAG","CBA_556x45_STANAG_L","CBA_556x45_STANAG_XL","CBA_556x45_STANAG_2D","CBA_556x45_STANAG_2D_XL"]
arifle_SPAR_02_base_F - ["STANAG_556x45_Large","CBA_556x45_STANAG","CBA_556x45_STANAG_L","CBA_556x45_STANAG_XL","CBA_556x45_STANAG_2D","CBA_556x45_STANAG_2D_XL"]
arifle_SPAR_03_base_F - ["CBA_762x51_HK417","CBA_762x51_HK417_L","CBA_762x51_HK417_XL"]
SMG_05_base_F - ["CBA_9x19_MP5"]
launch_MRAWS_base_F - ["CBA_Carl_Gustaf"]
```

**Comment by commy2** [comment]
close #1132

File: addons/jam/CfgWeapons.hpp [hunk 1]
```diff
@@ -6,76 +6,73 @@ class CfgWeapons {
     class Rifle_Short_Base_F;
 
     class mk20_base_F: Rifle_Base_F {
-        magazineWell[] = {"CBA_556x45_STANAG", "CBA_556x45_STANAG_L", "CBA_556x45_STANAG_XL", "CBA_556x45_STANAG_2D"};
+        magazineWell[] = {"STANAG_556x45", "CBA_556x45_STANAG", "CBA_556x45_STANAG_L", "CBA_556x45_STANAG_XL", "CBA_556x45_STANAG_2D"};
```
Comment (dedmen) [inline addons/jam/CfgWeapons.hpp]: Maybe we should just use += ? 
Currently we also break any mod that gets loaded before CBA and tries to add magwells.

Comment (commy2) [reply addons/jam/CfgWeapons.hpp]: Can you even += with all the inheritance going on?

Comment (dedmen) [reply addons/jam/CfgWeapons.hpp]: Sure. If a subclass just uses `=` that will not be of any use. But that would also break our `=` in the base class so that doesn't matter.
Just need to make sure that requiredAddons is correct, which is already correct.

Comment (commy2) [reply addons/jam/CfgWeapons.hpp]: += also fails horribly if the magazineWell token is inherited. I guess I will have to check all classes, but thankfully I have the config dumps.

Comment (dedmen) [reply addons/jam/CfgWeapons.hpp]: wasn't += built to work with inheritance? so that you can just add elements instead of overwriting..

Comment (commy2) [reply addons/jam/CfgWeapons.hpp]: No. It breaks for inherited tokens, but it works for different config patches adding to the same class.

Comment (commy2) [reply addons/jam/CfgWeapons.hpp]: It even breaks in funny ways like adding the same array element twice overwriting the old ones. It goes completely bonkers. It is a terrible idea to rely on it for this stuff, but whatever rocks there boat. I will quickly eat something and then do what we need to in CBA and ACE PRs. Gimme a minute.
